### ISSUE TITLE
Ko-fi support section

### ISSUE THREAD

**Issue by nemo83** [kimcc/hugo-theme-noteworthy#15]
Hi,

I have a blog that uses this template and I was wondering if it was possible to support the [ko-fi](https://ko-fi.com/) donation platform by adding an optional section at the end of a blogpost.

Ideally we'd want a property in the `config.toml` with the ko-fi id, and a flag, default to false in every blogpost to enable the ko-fi donate button.

WDYT?

Thanks,
Gio

**Comment by kimcc** [comment]
Hi @nemo83 I've added support for Ko-fi in the latest update. You can add it basically like how you specified in your post.

**Comment by nemo83** [comment]
@kimcc , you're a legend. Thanks!
