### ISSUE TITLE
Additional icons for links to social accounts

### ISSUE THREAD

**Issue by hinkelman** [kimcc/hugo-theme-noteworthy#2]
Is it possible to add links to accounts other than those included in the example site (e.g., twitter, github)? The three that I'm most interested in are google-scholar, impactstory, and orcid. Thanks.

**Comment by kimcc** [comment]
Hi @hinkelman, thanks for your interest in this theme. I've added icons for Google Scholar, ImpactStory and Orcid.

**Comment by hinkelman** [comment]
Thanks for providing those additional icons! Just a heads up that I had to remove the hyphen from `google-scholar` in `config.toml` and `social.html` to get the Google Scholar link to work. Thanks again!

**Comment by kimcc** [comment]
Thanks! I've made the fix in the latest update.
