### ISSUE TITLE
social links values

### ISSUE THREAD

**Issue by adfi** [kimcc/hugo-theme-noteworthy#3]
Hi, I'm having trouble finding out what values I should put in for the social links in the TOML. For example, for twitter I assume I would put in my twitter handle. However after deployment the link isn't pointing to twitter but to my own website. Even on https://themes.gohugo.io/theme/hugo-theme-noteworthy/, the links are pointing back to the website and not to the social sites.

**Comment by hinkelman** [comment]
I used the full url's. Here is my [config.toml](https://github.com/hinkelman/personal-website/blob/master/config.toml).
