### ISSUE TITLE
change config.toml to get Google Analytics to work

### ISSUE THREAD

**Issue by hinkelman** [kimcc/hugo-theme-noteworthy#4]
Following [this solution](https://stackoverflow.com/questions/46162211/google-analytics-does-not-work-with-blogdown/46207854#46207854), I had to move the Google Analytics line in my [config.toml](https://github.com/hinkelman/personal-website/blob/master/config.toml) above `[taxonomies]` to get tracking to work. Not sure if it is just a blogdown issue or a broader issue.

**Comment by kimcc** [comment]
Hi @hinkelman, I've moved Google Analytics as well as Disqus up in the config file.
