### ISSUE TITLE
Minified js not eligible for integrity checks since it’s neither CORS-enabled nor same-origin

### ISSUE THREAD

**Issue by jakehell** [kimcc/hugo-theme-noteworthy#8]
Hello,

When using the noteworthy theme in my hugo site, the server will launch successfully using the command `hugo server`.

However, the site itself seems to be missing some visual elements.

When I look at the console tab, I get the following error:

`“http://localhost:1313/js/main.min.fa5c2b23e07b5d9bfad267a52b4b24fdb053e6fb7524993383594926a3ac270c.js” is not eligible for integrity checks since it’s neither CORS-enabled nor same-origin.`

I do not get this error when using other themes.

Let me know if any further information is needed/could be useful.

Thanks

**Comment by kimcc** [comment]
@jakehell This should be fixed in the latest update, but let me know if this is still an issue.
